apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/
        backend:
          serviceName: api-service
          servicePort: 80
      - path: /
        backend:
          serviceName: ui-service
          servicePort: 80

