---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy
  labels:
    name: dummy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: dummy
    spec:
      containers:
      - name: dummy
        image: elitescrumteam/dummyservice:v6
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
