apiVersion: v1
kind: Service
metadata:
  name: interest-group-service
  labels:
    name: interest-group-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: interest-group
