---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
      - name: user
        image: elitescrumteam/user-service:v23
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
