---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: warning
  labels:
    name: warning
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: warning
    spec:
      containers:
      - name: warning
        image: elitescrumteam/warning-service:v38
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
